title: Alice Ji
description: >
  PhD Candidate in Media & Communication  
  <br>rji3@illinois.edu
theme: jekyll-theme-minimal

# This creates your top navbar.
navigation:
  - title: About
    url: /
  - title: CV
    url: /cv
  - title: Research
    url: /research

<style>
  nav a:hover {
    text-decoration: underline;
    color: #0056b3;
  }
</style>

# Optional: social links
google_analytics: false
