title: Alice Ji
description: PhD Student in Media & Communication  
theme: jekyll-theme-minimal

# Link to style.css
defaults:
  - scope:
      path: ""
    values:
      css: "/assets/style.css"

# Optional: social links
google_analytics: false
